nfl_analytics_theme <- function(..., base_size = 12) {
  theme(
    text = element_text(family = "Roboto", size = base_size),
    axis.ticks = element_blank(),
    axis.title = element_text(color = "black",
                              face = "bold"),
    axis.text = element_text(color = "black",
                             face = "bold"),
    plot.title.position = "plot",
    plot.title = element_text(size = 16,
                              face = "bold",
                              color = "black",
                              vjust = .02,
                              hjust = 0.5),
    plot.subtitle = element_text(color = "black",
                                 hjust = 0.5),
    plot.caption = element_text(size = 8,
                                face = "italic",
                                color = "black"),
    panel.grid.minor = element_blank(),
    panel.grid.major =  element_line(color = "#d0d0d0"),
    panel.background = element_rect(fill = "#f7f7f7"),
    plot.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_blank())
}